env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react/jsx-runtime'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react-hooks/recommended'
settings:
  react:
    version: 'detect'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - 'react'
  - '@typescript-eslint'
  - 'react-hooks'
  - 'simple-import-sort'
  - 'unused-imports'
  - 'prettier'
overrides:
  - files:
      - src/**/*
rules:
  prettier/prettier: warn
  simple-import-sort/imports: warn
  simple-import-sort/exports: warn
  no-debugger: warn
  no-console:
    - warn
    - allow: ['warn', 'error']
  react/prop-types: off
  react/display-name: off
